
import __ASTRO_IMAGE_IMPORT_1dN3xl from "@assets/images/blog/update.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fopen-release-phase.mdx";
import __ASTRO_IMAGE_IMPORT_19jIHu from "@assets/images/blog/update.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fel%2Fopen-release-phase.mdx";
import __ASTRO_IMAGE_IMPORT_Z1hiVJB from "@assets/images/blog/early-access-update.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fearly-access-update.mdx";
import __ASTRO_IMAGE_IMPORT_Z5enNU from "@assets/images/blog/update.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fhappy-new-year.mdx";
import __ASTRO_IMAGE_IMPORT_1hdWNr from "@assets/images/blog/notificator-banner.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fwelcome-to-the-blog.mdx";
import __ASTRO_IMAGE_IMPORT_ZFpU6J from "@assets/images/blog/wp-notificator-wcath25-c.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fwp-notificator-at-wordcamp-athens-2025.mdx";
import __ASTRO_IMAGE_IMPORT_Z1WxYCO from "@assets/images/blog/wp-notificator-wcath25-b.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fwp-notificator-at-wordcamp-athens-2025.mdx";
import __ASTRO_IMAGE_IMPORT_ZQJXfU from "@assets/images/blog/wp-notificator-wcath25.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fwp-notificator-at-wordcamp-athens-2025.mdx";
export default new Map([["@assets/images/blog/update.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fopen-release-phase.mdx", __ASTRO_IMAGE_IMPORT_1dN3xl], ["@assets/images/blog/update.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fel%2Fopen-release-phase.mdx", __ASTRO_IMAGE_IMPORT_19jIHu], ["@assets/images/blog/early-access-update.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fearly-access-update.mdx", __ASTRO_IMAGE_IMPORT_Z1hiVJB], ["@assets/images/blog/update.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fhappy-new-year.mdx", __ASTRO_IMAGE_IMPORT_Z5enNU], ["@assets/images/blog/notificator-banner.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fwelcome-to-the-blog.mdx", __ASTRO_IMAGE_IMPORT_1hdWNr], ["@assets/images/blog/wp-notificator-wcath25-c.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fwp-notificator-at-wordcamp-athens-2025.mdx", __ASTRO_IMAGE_IMPORT_ZFpU6J], ["@assets/images/blog/wp-notificator-wcath25-b.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fwp-notificator-at-wordcamp-athens-2025.mdx", __ASTRO_IMAGE_IMPORT_Z1WxYCO], ["@assets/images/blog/wp-notificator-wcath25.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fwp-notificator-at-wordcamp-athens-2025.mdx", __ASTRO_IMAGE_IMPORT_ZQJXfU]]);
		