
import __ASTRO_IMAGE_IMPORT_1VQOkg from "@assets/images/projects/lightcraft.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fen%2Flightcraft.mdx";
import __ASTRO_IMAGE_IMPORT_DRjl4 from "@assets/images/projects/studiovision.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fen%2Fstudiovision.mdx";
import __ASTRO_IMAGE_IMPORT_Z2t2HDJ from "@assets/images/projects/artisanlens.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fit%2Fartisanlens.mdx";
import __ASTRO_IMAGE_IMPORT_12dKH1 from "@assets/images/projects/lightcraft.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fit%2Flightcraft.mdx";
import __ASTRO_IMAGE_IMPORT_mNoGd from "@assets/images/projects/artisanlens.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fen%2Fartisanlens.mdx";
import __ASTRO_IMAGE_IMPORT_ZJ33Jg from "@assets/images/projects/pixelcraft.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fen%2Fpixelcraft.mdx";
import __ASTRO_IMAGE_IMPORT_Z1DG7mv from "@assets/images/projects/pixelcraft.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fit%2Fpixelcraft.mdx";
import __ASTRO_IMAGE_IMPORT_Z1fdWnw from "@assets/images/projects/studiovision.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fit%2Fstudiovision.mdx";
import __ASTRO_IMAGE_IMPORT_Zwsaan from "@assets/images/authors/mintaka.png?astroContentImageFlag=&importer=src%2Fcontent%2Fauthors%2Fen%2Fmarcus-chen.md";
import __ASTRO_IMAGE_IMPORT_ZFpU6J from "@assets/images/blog/wp-notificator-wcath25-c.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fwp-notificator-at-wordcamp-athens-2025.mdx";
import __ASTRO_IMAGE_IMPORT_Z1WxYCO from "@assets/images/blog/wp-notificator-wcath25-b.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fwp-notificator-at-wordcamp-athens-2025.mdx";
import __ASTRO_IMAGE_IMPORT_ZQJXfU from "@assets/images/blog/wp-notificator-wcath25.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fwp-notificator-at-wordcamp-athens-2025.mdx";
import __ASTRO_IMAGE_IMPORT_Z1r6dMC from "@assets/images/authors/mintaka.png?astroContentImageFlag=&importer=src%2Fcontent%2Fauthors%2Fit%2Fmarcus-chen.md";
import __ASTRO_IMAGE_IMPORT_Z5enNU from "@assets/images/blog/update.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fhappy-new-year.mdx";
import __ASTRO_IMAGE_IMPORT_Z1hiVJB from "@assets/images/blog/early-access-update.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fearly-access-update.mdx";
import __ASTRO_IMAGE_IMPORT_1hdWNr from "@assets/images/blog/notificator-banner.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fwelcome-to-the-blog.mdx";
export default new Map([["@assets/images/projects/lightcraft.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fen%2Flightcraft.mdx", __ASTRO_IMAGE_IMPORT_1VQOkg], ["@assets/images/projects/studiovision.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fen%2Fstudiovision.mdx", __ASTRO_IMAGE_IMPORT_DRjl4], ["@assets/images/projects/artisanlens.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fit%2Fartisanlens.mdx", __ASTRO_IMAGE_IMPORT_Z2t2HDJ], ["@assets/images/projects/lightcraft.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fit%2Flightcraft.mdx", __ASTRO_IMAGE_IMPORT_12dKH1], ["@assets/images/projects/artisanlens.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fen%2Fartisanlens.mdx", __ASTRO_IMAGE_IMPORT_mNoGd], ["@assets/images/projects/pixelcraft.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fen%2Fpixelcraft.mdx", __ASTRO_IMAGE_IMPORT_ZJ33Jg], ["@assets/images/projects/pixelcraft.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fit%2Fpixelcraft.mdx", __ASTRO_IMAGE_IMPORT_Z1DG7mv], ["@assets/images/projects/studiovision.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fit%2Fstudiovision.mdx", __ASTRO_IMAGE_IMPORT_Z1fdWnw], ["@assets/images/authors/mintaka.png?astroContentImageFlag=&importer=src%2Fcontent%2Fauthors%2Fen%2Fmarcus-chen.md", __ASTRO_IMAGE_IMPORT_Zwsaan], ["@assets/images/blog/wp-notificator-wcath25-c.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fwp-notificator-at-wordcamp-athens-2025.mdx", __ASTRO_IMAGE_IMPORT_ZFpU6J], ["@assets/images/blog/wp-notificator-wcath25-b.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fwp-notificator-at-wordcamp-athens-2025.mdx", __ASTRO_IMAGE_IMPORT_Z1WxYCO], ["@assets/images/blog/wp-notificator-wcath25.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fwp-notificator-at-wordcamp-athens-2025.mdx", __ASTRO_IMAGE_IMPORT_ZQJXfU], ["@assets/images/authors/mintaka.png?astroContentImageFlag=&importer=src%2Fcontent%2Fauthors%2Fit%2Fmarcus-chen.md", __ASTRO_IMAGE_IMPORT_Z1r6dMC], ["@assets/images/blog/update.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fhappy-new-year.mdx", __ASTRO_IMAGE_IMPORT_Z5enNU], ["@assets/images/blog/early-access-update.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fearly-access-update.mdx", __ASTRO_IMAGE_IMPORT_Z1hiVJB], ["@assets/images/blog/notificator-banner.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fen%2Fwelcome-to-the-blog.mdx", __ASTRO_IMAGE_IMPORT_1hdWNr]]);
		